version: "3.9"
services:
  someService:
    image: redis:alpine
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: 0.5
          memory: 1G
  someOtherService:
    image: redis:alpine
    deploy:
      replicas: 2
      resources:
        limits:
          testWrongLimit: 1
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
  myService:
    image: redis:alpine
