version: "3.9"
services:
  jobmanager:
    image: jfr212/jfr_flink
    ports:
      - "8081"
    command: standalone-job --job-classname org.apache.flink.streaming.examples.wordcount.WordCount -input /opt/flink/usrlib/artifacts/bible.txt
    volumes:
      - /opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5G"
      labels:
        nodetype: "coordinator"
      restart_policy:
        condition: none
  taskmanager:
    image: jfr212/jfr_flink
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - /opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5G"
      labels:
        nodetype: "worker"
      restart_policy:
        condition: none
