# CI to deploy Node.js App on the swarm leader node
name: CI
on:
  push:
    branches:
      - master
      - deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.1.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Set Env Variables
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Restart Appplication with pm2
        run: pm2 restart NodeApp
      - name: create deploy directory
        run: mkdir deploy
